### PR TITLE
some changes were occured

### PR DESCRIPTION
**Pull request by TohirjonIbnAlisher**

### CODE REVIEW

**Review by Ozod007 — CHANGES_REQUESTED** [review]
code was not accepted
requested change

**Comment by TohirjonIbnAlisher** [comment]
changed

**Review by Ozod007 — APPROVED** [review]

**Comment by Inamdjanof** [comment]
ok

**Comment by azamatzv** [comment]
savsx

**Review by azamatzv — APPROVED** [review]

**Review by Inamdjanof — APPROVED** [review]

**Pull request merged**
